### ISSUE TITLE
Points for tasks

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#10]
Do we have points for tasks? it would be nice and doesn't seem hard to implement. @KovaxG would that be hard in dbhandler?

**Comment by KovaxG** [comment]
Couldn't we use the Observations field?

**Comment by RobertKajnak** [comment]
I do not see how Oservations is in any way suggestive of awarded points.

**Comment by KovaxG** [comment]
Observation, user has x points.

**Comment by RobertKajnak** [comment]
Are you serious? :|

**Comment by KovaxG** [comment]
Besides, tasks don't have points either. You would need to add points to tasks and users also.

**Comment by RobertKajnak** [comment]
Not enough time to implement
