### ISSUE TITLE
CreateTask

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#11]
Can create 2 identical tasks within the same project.  Suggestion: title and shortDescription should be unique

**Comment by KovaxG** [comment]
That was deliberate. Two projects may have both a task that has the same title and same description. Maybe I could check if they both are from the same project, they cannot be identical.

**Comment by RobertKajnak** [comment]
Maybe you could not maybe do something but, do it and only AFTERWARDS close the issue. Your sentances are too ambigous

**Comment by KovaxG** [comment]
Ok, I will not close issues only after confirmation.
