### ISSUE TITLE
maximum task duration

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#12]
We talked about this: what is the maximum duration for a task? 
I currently set it to minimum 10 minutes and maximum 3 months

**Comment by KovaxG** [comment]
Make it a variable.

**Comment by RobertKajnak** [comment]
What does that even mean? It is defined by us, it doesn't change, why would it be a variable? Indefinitely long maybe, but why variable?
And I would like the input of the other two members( @ramonabolboaca13 ; @Alex-Barabasi ) before closing this topic

**Comment by KovaxG** [comment]
A variable as in store it somewhere and make it so we can modify it later.
