### ISSUE TITLE
TaskData - status

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#15]
We need to clarify what are the possible values. Also: the default value should be one of those, not " - "
I don't even remember why we needed this
My thoughts are: 
Completed (CompletedBy != 0)
Tackling (Completed by==0 && (COUNT Users.ActiveTask==Task.ID)==1)
Idle (Completed by==0 && (COUNT Users.ActiveTask==Task.ID)==0)
Requested (Completed by==0 && (COUNT taskrequests.Task_ID==Task.ID)>0)
~~Failed~~ Overdue (Deadline-current time<0 && CompletedBy==0) 

We can remove the field and just implement a method in dbhandler that returns one of these values

**Comment by KovaxG** [comment]
I suggest renaming Failed to Overdue.

**Comment by RobertKajnak** [comment]
Agreed

**Comment by KovaxG** [comment]
Problem: A task can be both **Idle and Requested** and **Tackling and Requested** and **Overdue and Requested**. (In our current state also _Completed and Requested_). What do I do? For now I will leave it out, and add an Error message;

Implemented `public string TaskStatus(TaskData task)`

**Comment by RobertKajnak** [comment]
Tacking and requested = Tacking (if someone is already doing it, don't look at grass is greener if some one else does it and kick current person)
Overdue and requested = Overdue (just assign someone already)
Idle and requested = Requested (because the others exclude this way)

**Comment by KovaxG** [comment]
Done. I think.

**Comment by RobertKajnak** [comment]
Resolved. Status now freed up for other purposes like completion link
