### ISSUE TITLE
TaskData - Created By

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#16]
Remains 0

**Comment by KovaxG** [comment]
Did you use the correct constructor? `TaskData newTask = new TaskData(User.ID);` ?

**Comment by RobertKajnak** [comment]
I still do not see that is not the implicit value on construction. How does it make sense to create a task without a creator?

**Comment by KovaxG** [comment]
You shouldn't use the default constructor. I made it for inserting tasks, you were never meant to use it. If you want I could remove it.

**Comment by RobertKajnak** [comment]
Set those to private please. What I meant that when i create a task, the only person from which I should be creating tasks is the user I am logged in with, right?

**Comment by KovaxG** [comment]
There are instances when I need a task where the CreatedBy is blank. Yes, only the user can create new tasks.

**Comment by RobertKajnak** [comment]
Understood
