### ISSUE TITLE
DatabaseHandler method for Team Member

### ISSUE THREAD

**Issue by Alex-Barabasi** [KovaxG/Taskr#20]
Need method which returns the active task of the currently logged in user.

**Comment by RobertKajnak** [comment]
Gyuri here:
Not yet implemented, will implement when I get home, for now use this command:
`TaskData myTask = handler.GetTasksForProject(handler.GetCurrentProject()).Find(t => t.ID == User.ActiveTask);`

Be carefull, might be null!

**Comment by KovaxG** [comment]
The function is called `GetActiveTask()`
