### ISSUE TITLE
does the user have the task?

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#21]
What is the name of the method with which i can see if someone is already working on a given task? I konw you have implemented this check in the GrantTask method (UserData tempUser = GetAllUsers ().Find (u => u.ActiveTask == task.ID);).

**Comment by RobertKajnak** [comment]
And it would maybe return the user who is working on it or null if nobody is

**Comment by KovaxG** [comment]
Implemented `public UserData GetUserWorkingOnTask(TaskData task)`

**Comment by RobertKajnak** [comment]
Works
