### ISSUE TITLE
Thread Exception

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#26]
this.Invoke(d, new object[] { }); gives exception several minutes into runtime

**Comment by KovaxG** [comment]
What is that?

**Comment by RobertKajnak** [comment]
I have no ideea, it poped up after I left the program running for several minutes. I couldn't replicate it

**Comment by KovaxG** [comment]
Solar radiation?

**Comment by RobertKajnak** [comment]
I think it is fixed, but still unsure. It might have been
