### ISSUE TITLE
CancelTaskRequest

### ISSUE THREAD

**Issue by Alex-Barabasi** [KovaxG/Taskr#29]
Method not working properly ( reminder for Kovacs ),

**Comment by RobertKajnak** [comment]
You can use @KovaxG to mark people, Github should bring up a list, if you press '@'

**Comment by Alex-Barabasi** [comment]
@KovaxG

**Comment by Alex-Barabasi** [comment]
Found problem. Table is called "taskrequests" not "tasksrequests".

**Comment by Alex-Barabasi** [comment]
@KovaxG please correct in DatabaseHandler.
