### ISSUE TITLE
returned errors differentiation

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#3]
A sort of exception throw or object return needs to be implemented on functions that are not always correctly executed such as joinProject -- if the join request has already been sent, it returns something, if the connection lost, returns something else etc

Remark:
using throw would allow to use return for other purpose
 Example:
bool HasAlreadyRequestedJoin(ProjectData project) -- true/false for answer and exception for verification failure. Ofc an int could be used to combine the two, but I find this more intuitive, though i am still open for counter arguments

**Comment by RobertKajnak** [comment]
It makes life harder to debug without these, even if it will take some work. When the error message "could not do just because" pops up, it is not in the least helpful. I am tending towards the throws thing. It allows to use return for different purpose. And since it is an error(close to exception) it somewhat fits. But I willl listen to counter arguments.

**Comment by KovaxG** [comment]
Removing all try-catch blocks from the databasehandler, so you will need to surround them with try catch, and in the catch just show the message. Also:

# **Massive Painful Changes to the DataBaseHandler**
