### ISSUE TITLE
The team leader is part of the team

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#30]
This is in order right? He can assign a task to himselft, and through edit task can complete any fields himself

**Comment by RobertKajnak** [comment]
Now it's sort of like close on Github, but you can't reopen it (so that the team leader can't open it, edit it, then reclose it)

**Comment by KovaxG** [comment]
Do you mean that the TL cannot edit a completed task? What are you referring to with 

> Now it's sort of like close on Github,

What is the "it"?
