### ISSUE TITLE
Removing active task from user

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#31]
when i change a task to completed, I can only change the details of the task, but not the users, leaving the user with a completed task as working on.

**Comment by KovaxG** [comment]
Why not use drop task?

**Comment by RobertKajnak** [comment]
Because it drops my task, not the other team member's, who completed it

**Comment by KovaxG** [comment]
Wait a minute, you as the teamLeader want to change the status of the task that is currently being worked on by a teamMember? Did we allow that?

**Comment by RobertKajnak** [comment]
I want to mark it as completed

**Comment by KovaxG** [comment]
To be clear, you want to set `user.ActiveTask = 0;` ? or do you want to set the task to be completed? like `task.CompletedBy = theUserWhoWorksOnIt.ID` ?

**Comment by RobertKajnak** [comment]
if (d.GetUserWorkingOnTask(taskData)!= null)
                {
                    taskData.CompletedBy = worker.ID;
                    //now Remove the Task from the  user
                }
=>first variant

**Comment by KovaxG** [comment]
the code is basically: `user.ActiveTask = DBDefaults.DefaultId;`. Should I make a function?

**Comment by RobertKajnak** [comment]
Please do so

**Comment by KovaxG** [comment]
Added `public bool RemoveActiveTaskForUser (UserData user)`

**Comment by RobertKajnak** [comment]
Works fine now. Thank you
