### ISSUE TITLE
UpdateTask exception

### ISSUE THREAD

**Issue by Alex-Barabasi** [KovaxG/Taskr#33]
Throws exception at command.ExecuteNonQuery() for unknown reason.
Checked TaskData taken as parameter, looks normal.
@KovaxG any ideas?

**Comment by KovaxG** [comment]
How? I tried some stuff, got no exception. Any advice to try to reproduce?

**Comment by Alex-Barabasi** [comment]
This is the code:
TaskData td = d.GetActiveTask();

```
        td.Notes = this.textBoxLinkUploadFiles.Text;

        if (d.UpdateTask(td))
        {
            MessageBox.Show("Submission successfully sent.");
        }
        else
        {
            MessageBox.Show("Submission was not sent.");
        }
```

**Comment by KovaxG** [comment]
Could notes be null? Maybe that is the problem?

**Comment by Alex-Barabasi** [comment]
Nope.

**Comment by Alex-Barabasi** [comment]
this.textBoxLinkUploadFiles.Text always returns a string. It may be an empty string but not null. I debugged it and as I said before found that the command.ExecuteNonQuery() throws the exception.

**Comment by KovaxG** [comment]
Be sure to make a check, if it is emptystring make it a `DBDefaults.DefaultText` or in other words:

```
string text = this.textBoxLinkUploadFiles.Text;
if (text == "") text = DBDefaults.DefaultText;
td.Notes = text;
```

Still couldn't reproduce.

**Comment by KovaxG** [comment]
It was the date.
