### ISSUE TITLE
InsertProject

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#4]
It should make you its team leader automatically
-- on same note: which fields are compulsory to complete? title and shortDescription?

**Comment by KovaxG** [comment]
It actually does: `ProjectData newProject = new ProjectData(User.ID);`, this sets the createdBy and teamLeader fields to User.ID.

**Comment by RobertKajnak** [comment]
It doesn't, nor does it make you join it. Created by and ProjectLead and ActiveProject are left 0

**Comment by KovaxG** [comment]
Impossible. If you use it like that, CreatedBy and ProjectLead are set. I will include also ActiveProject.

**Comment by RobertKajnak** [comment]
Why doesn't it do that with the default constructor?

**Comment by KovaxG** [comment]
Because the default Constructor actually calls the Constructor with the ID, with DefaultId.

**Comment by RobertKajnak** [comment]
But why not user.ID? Isn't that the default case: when the user creates a project. Who else would?

**Comment by KovaxG** [comment]
Yes, but if you want to implement it like that, I would have to send an instance of the databaseHandler to the projectData. I don't see the problem, just call the correct constructor. If you wish I will remove the default constructor.
