### ISSUE TITLE
CancelJoinRequest

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#6]
Do we need this? It would be nice, but doesn't seem critical. @KovaxG : if you think it is, create the function in databashandler and i will to the graphics

**Comment by KovaxG** [comment]
Maybe if you join an embarrassing project, like "a social netowrk for goatlovers to express themselves.". I will add.

**Comment by KovaxG** [comment]
Done.

**Comment by RobertKajnak** [comment]
Done on GUI side as well.
