### ISSUE TITLE
VerifyLogin

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#7]
1. SELECT \* FROM users WHERE DisplayName LIKE 'Traian' AND PasswordHash LIKE 'passwordtraian8';
   = should be used instead of LIKE. The latter allows for wildcards (normally allowed in passwords); as such 
   SELECT \* FROM users WHERE DisplayName LIKE 'Traian' AND PasswordHash LIKE '%'; would allow access, while SELECT \* FROM users WHERE DisplayName LIKE 'Traian' AND PasswordHash = '%' would not. 
   SELECT \* FROM users WHERE DisplayName ='Traian' AND PasswordHash = 'passwordtraian8'; works correctly. 
2. Hash still not implemented. BUT we need to be careful as not to forget the passwords, as you cannot descifer them from the hash (which is the entire point)

**Comment by KovaxG** [comment]
When adding hashes, we need to make changes to the inserts. We need to insert the hashes into the database. I will put '=' instead of 'LIKE', but hashes will have to wait for now.

**Comment by KovaxG** [comment]
Problem: The hash takes 2 arguments, the password and the user ID as salt. How do I get the user ID, without logging on? I could just take all the users and try every ID until something works, but still I recommend using the displayName as salt, because it too is unique anyway.

**Comment by RobertKajnak** [comment]
You can get the ID from the display name, it's unique if I'm not mistaken. 
See Ramona's work:
 "Select Id from secretary where (Email=@username or DisplayName = @username) and LeaveDate=@DefaultDate";

**Comment by KovaxG** [comment]
Couldn't we use the length of the DisplayName or something? Seems more straight forward.

**Comment by RobertKajnak** [comment]
The length of the display name is not OK, the salt needs to be unique for each user. It would not be that uncommon for 2 users to have the same username length

**Comment by KovaxG** [comment]
Can't we use the DisplayName itself somehow?

**Comment by RobertKajnak** [comment]
Why are you so against  using Ramona's code? Would it take that much time?

**Comment by KovaxG** [comment]
Fine.

**Comment by KovaxG** [comment]
Implemented the login. I tried it and it works for me.

**Comment by RobertKajnak** [comment]
Indeed it does
