### ISSUE TITLE
AbolishProject

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#8]
Should make all team members leave the project. Leave project normally works, but when called from within AbolishProject it doesn't. Wierd.

**Comment by KovaxG** [comment]
Weird because GetCurrentProject didn't work correctly. Now it does.

**Comment by RobertKajnak** [comment]
Returns false, gets you out of the project, but project remains unmodified: you are its team leader and creator, but you are not part of the project

**Comment by KovaxG** [comment]
LeaveProject didn't let you leave if you were teamleader, made modifications.
