### ISSUE TITLE
FillDataRow - Users

### ISSUE THREAD

**Issue by RobertKajnak** [KovaxG/Taskr#9]
AvatarURL          =                row.ItemArray.GetValue (4).ToString ();
returns DisplayName value instead of AvatarURL value. No @#!%ing  idea why. The problem could be on my part, but I can't  find it. Any help would be appreciated

**Comment by KovaxG** [comment]
Solved, the problem was that the getter was returning the displayName. That is why copy paste may lead you to a road of frustration.
